openapi: 3.0.1
info:
  title: File Upload API
  version: 1.0.0
servers:
 - url: http://localhost:8080/api
   description: Local Server
paths:
  /fileDelivery:
    post:
      summary: Relay File to Production API
      operationId: sendFile
      tags: 
        - File Sending
      parameters:
        - name: filename
          in: query
          description: The name of the file to relay
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileSchema' 
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

components:
  schemas:
    FileSchema:
      type: object
      properties:
        file:
          type: string
          format: binary
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string